### PR TITLE
point amoebanet kubefile to official source

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by brettkoonce** [comment]
also, for the record, this instantly OOM's even when it does run.

**Comment by brettkoonce** [comment]
the following is failing for me if you want to try it.  above tweak + preemptible tpu + a bucket are the only changes.

https://gist.github.com/brettkoonce/0b2ffd6c6572f98895a412ea7cc9081b

**Comment by brettkoonce** [comment]
https://gist.github.com/brettkoonce/0b2ffd6c6572f98895a412ea7cc9081b

above fails:

screen shot 2019-02-13 at 11 32 58 am

**Comment by brettkoonce** [comment]
screen shot 2019-02-13 at 11 43 10 am
screen shot 2019-02-13 at 11 43 20 am
screen shot 2019-02-13 at 11 43 25 am

**Comment by brettkoonce** [comment]
@frankchn still an issue in 1.13.

**Comment by yguo0905** [comment]
LGTM.

@frankchn, can you please review this?

**Pull request merged**
